// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrhU9DWwlEbBBrVyBd0dE7HVeF4Zts8GU',
    appId: '1:685293846978:web:a1a6cbb83e60e2e28dd65b',
    messagingSenderId: '685293846978',
    projectId: 'mio-wallet-330f1',
    authDomain: 'mio-wallet-330f1.firebaseapp.com',
    storageBucket: 'mio-wallet-330f1.firebasestorage.app',
    measurementId: 'G-WGDE1B41MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_G5YnW7CnGH8ozrpxMtUj0FUg9LOCJRE',
    appId: '1:685293846978:android:172a8cdf5dcc2ea08dd65b',
    messagingSenderId: '685293846978',
    projectId: 'mio-wallet-330f1',
    storageBucket: 'mio-wallet-330f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVQCZmtKVQXqXoBjXHsZPeFmBRrcXSEKk',
    appId: '1:685293846978:ios:0cf76e283cc57f3a8dd65b',
    messagingSenderId: '685293846978',
    projectId: 'mio-wallet-330f1',
    storageBucket: 'mio-wallet-330f1.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVQCZmtKVQXqXoBjXHsZPeFmBRrcXSEKk',
    appId: '1:685293846978:ios:0cf76e283cc57f3a8dd65b',
    messagingSenderId: '685293846978',
    projectId: 'mio-wallet-330f1',
    storageBucket: 'mio-wallet-330f1.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrhU9DWwlEbBBrVyBd0dE7HVeF4Zts8GU',
    appId: '1:685293846978:web:2eb5b535b90059f28dd65b',
    messagingSenderId: '685293846978',
    projectId: 'mio-wallet-330f1',
    authDomain: 'mio-wallet-330f1.firebaseapp.com',
    storageBucket: 'mio-wallet-330f1.firebasestorage.app',
    measurementId: 'G-EJV545N8ZL',
  );
}
